
project_id = "ixqtnqvdwhqnpjwjqzpx"

[functions.checkout-boleto]
verify_jwt = false

[functions.click2pay-integration]
verify_jwt = false

[functions.click2pay-webhook]
verify_jwt = false

[functions.payment-refund]
verify_jwt = false

[functions.payment-status]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.simulate-webhook]
verify_jwt = false

[functions.simulate-payment-confirmed]
verify_jwt = false
